name: Deploy Eatmoji to Personal Repo

on:
  push:
    branches:
      - develop  # or main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Copy eatmoji directory
        run: |
          mkdir output
          cp -R ./eatmoji/* ./output/

      - name: Push to personal repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_DEPLOYMENT }}
        with:
          source-directory: 'output'
          destination-github-username: 'Head-ddy'
          destination-repository-name: 'Eatmoji_FE'
          destination-repository-username: 'Head-ddy'
          target-branch: 'develop'
          commit-message: 'chore: deploy eatmoji from team repo'
