name: git push into another repo to deploy to vercel

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eatmoji
    steps:
      - uses: actions/checkout@v2

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_DEPLOYMENT }}
        with:
          source-directory: '../output'
          destination-github-username: Head-ddy
          destination-repository-name: Eatmoji_FE
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: "chore: deploy eatmoji from team repo"
          target-branch: develop
